apiVersion: v1
kind: Service
metadata:
  name: appointments-service
spec:
  selector:
    app: appointments
  ports:
    - protocol: TCP
      port: 80
      targetPort: 7070
  type: NodePort

metadata:
  name: appointments-service

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: appointments-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appointments
  template:
    metadata:
      labels:
        app: appointments
    spec:
      initContainers:
        - name: init
          image: ubuntu:latest
          command: ["sh", "-c", "echo 'My name is Rayed Muhammad Saeed' && sleep 5"]
      containers:
        - name: appointments
          image: rayed14/appointments:136522209f2341dbf8d942f765b4eb4ec045625c 
          env:
            - name: NAME
              valueFrom:
                secretKeyRef:
                  name: appointment
                  key: NAME
            - name: PASSWORD
              valueFrom:
                secretKeyRef:
                  name: appointment
                  key: PASSWORD
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 7070
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 7070
            initialDelaySeconds: 15
            periodSeconds: 20