apiVersion: v1
kind: ConfigMap
metadata:
  name: doctors-config
data:
  details.txt: |
    My name is Rayed Muhammad Saeed and i am studying Devops.

---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    app: doctors
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  selector:
    matchLabels:
      app: doctors
  template:
    metadata:
      labels:
        app: doctors
    spec:
      initContainers:
        - name: init
          image: ubuntu:latest
          command: ["sh", "-c", "echo 'My name is Rayed Muhammad Saeed' && sleep 5"]
      containers:
        - name: doctors
          image: rayed14/doctors:1b6d1d24c594c3bccfc4e37fc39f9c206346d7ce 
          env:
        - name: APPOINTMENTS_API_HOST
          value: appointments-service
        - name: APPOINTMENTS_API_PORT
          value: "80"
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: config-volume
              mountPath: /user
      volumes:
        - name: config-volume
          configMap:
            name: doctors-config